version: '3'

services:
    app:
        container_name: app
        hostname: app
        build:
            context: .
        working_dir: /app
        # command: echo "Hello"
        tty: true
        env_file: .env
        environment:
        - PYTHONPATH=/app/src
        volumes:
        - .:/app:delegated
        - home:/home/$LOCAL_USER_NAME
        networks:
        - app-network

volumes:
    home:

networks:
    app-network:
